name: Sunbase
version: '${project.version}'
main: suncore.sunbase.Main
api-version: 1.20
authors: [ mythcore, yagah ]
commands:
  class:
    description: Change your player class
    usage: /class <classname>
