name: Sunbase
version: '${project.version}'
main: suncore.sunbase.Main
api-version: 1.20
authors: [ mythcore, yagah ]
commands:
  class:
    description: Change your player class
    usage: /class <classname>
  abilities:
    description: Check the abilities for each class
    usage: /abilities <classname>
  bind:
    description: Bind an ability to a hotbar slot.
    usage: /bind <ability> <slot>
